/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Automovel;
import Model.Caminhao;
import Model.Moto;
import Model.Veiculo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author CAROL
 */
public class Principal extends javax.swing.JFrame {

    private List<Veiculo> listaDeVeiculos = new ArrayList<Veiculo>();
    int contadorDePagina = 0;
    
      boolean validaCampoAutomovel(){
        if(txttipo.getText() != null ||
                txtmarca.getText() != null ||
                txtmodelo.getText() != null ||
                txtcor.getText() != null ||
                txtanofab.getText() != null ||
                txtplaca.getText() != null ||
                txtrenavam.getText() != null ||
                txtchassi.getText() != null ||
                txtid.getText() != null 
                        
                //adicionar aqui todos os campos *** adicinados
                ){
        return true;
        }else{
        return false;
                }
    }
    
      
     boolean validaCampoCaminhao(){
        if(txteixos.getText() != null ||
                txtmarca.getText() != null ||
                txtmodelo.getText() != null ||
                txtcor.getText() != null ||
                txtanofab.getText() != null ||
                txtplaca.getText() != null ||
                txtrenavam.getText() != null ||
                txtchassi.getText() != null ||
                txtid.getText() != null 
                        
                //adicionar aqui todos os campos *** adicinados
                ){
        return true;
        }else{
        return false;
                }
    }
  
    
    boolean validaCampoMoto(){
        if(txtcilindrada.getText() != null ||
                txtmarca.getText() != null ||
                txtmodelo.getText() != null ||
                txtcor.getText() != null ||
                txtanofab.getText() != null ||
                txtplaca.getText() != null ||
                txtrenavam.getText() != null ||
                txtchassi.getText() != null || 
                txtid.getText() != null
                        
                //adicionar aqui todos os campos **** adicionados
                ){
        return true;
        }else{
        return false;
                }
    }
  
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtcor = new javax.swing.JTextField();
        txtanofab = new javax.swing.JTextField();
        txtchassi = new javax.swing.JTextField();
        txtrenavam = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        txttipo = new javax.swing.JTextField();
        ckcarro = new javax.swing.JCheckBox();
        ckmoto = new javax.swing.JCheckBox();
        ckcaminhao = new javax.swing.JCheckBox();
        txtcilindrada = new javax.swing.JTextField();
        txteixos = new javax.swing.JTextField();
        btnproximo = new javax.swing.JButton();
        btnanterior = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Chassi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Veículos");
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(730, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro e Consulta de Veículos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 40));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        txtmodelo.setName("modelo"); // NOI18N
        getContentPane().add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));
        txtmodelo.getAccessibleContext().setAccessibleDescription("Modelo");

        getContentPane().add(txtcor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 30));

        txtanofab.setToolTipText("Ano Fab");
        getContentPane().add(txtanofab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 150, 30));
        getContentPane().add(txtchassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, 30));
        getContentPane().add(txtrenavam, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 150, 30));
        getContentPane().add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 150, 30));

        btnsalvar.setText(":::Salvar:::");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 90, 30));
        getContentPane().add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 150, 30));

        ckcarro.setSelected(true);
        ckcarro.setText("Carro");
        ckcarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckcarroActionPerformed(evt);
            }
        });
        getContentPane().add(ckcarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ckmoto.setText("Moto");
        ckmoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckmotoActionPerformed(evt);
            }
        });
        getContentPane().add(ckmoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, -1));

        ckcaminhao.setText("Caminhao");
        ckcaminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckcaminhaoActionPerformed(evt);
            }
        });
        getContentPane().add(ckcaminhao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, -1));

        txtcilindrada.setEnabled(false);
        getContentPane().add(txtcilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 150, 30));
        getContentPane().add(txteixos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 150, 30));

        btnproximo.setBackground(new java.awt.Color(153, 153, 255));
        btnproximo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnproximo.setForeground(new java.awt.Color(102, 102, 255));
        btnproximo.setText(">>>>");
        btnproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproximoActionPerformed(evt);
            }
        });
        getContentPane().add(btnproximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 71, -1));

        btnanterior.setBackground(new java.awt.Color(153, 153, 255));
        btnanterior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnanterior.setForeground(new java.awt.Color(102, 102, 255));
        btnanterior.setText("<<<<");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });
        getContentPane().add(btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 71, -1));

        jButton3.setText(":::Criar:::");
        jButton3.setPreferredSize(new java.awt.Dimension(60, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, -1));
        jButton3.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setText("Tipo de veículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel3.setText("Modelo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 244, 60, 20));

        Chassi.setText("Chassi");
        getContentPane().add(Chassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 100, 10));

        jLabel5.setText("Marca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 20));

        jLabel6.setText("Id veículo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        jLabel7.setText("Cor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 60, -1));

        jLabel8.setText("Ano de fabricação");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 100, -1));

        jLabel9.setText("Placa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 80, 20));

        jLabel10.setText("Quantidade de eixos");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 130, 20));

        jLabel11.setText("Renavam");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 80, 20));

        jLabel12.setText("Cilindradas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 80, 20));

        jLabel13.setText("Tipo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 80, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        String tipoSelecionado = "nenhum";
        if (ckcaminhao.isSelected()) {
            tipoSelecionado = "caminhao";
        } else if (ckcarro.isSelected()) {
            tipoSelecionado = "carro";
        } else if (ckmoto.isSelected()) {
            tipoSelecionado = "moto";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o valor ");
        }

        if (tipoSelecionado.equals("moto")) {
            if(validaCampoMoto() == true){
            int IdVeiculo = Integer.parseInt(txtid.getText());
            String chassi = txtchassi.getText();
            int ano = Integer.parseInt(txtanofab.getText());
            int renavam = Integer.parseInt(txtrenavam.getText());
            String marca = txtmarca.getText();
            String modelo = txtmodelo.getText();
            String cor = txtcor.getText();
            String placa = txtplaca.getText();
            int cilindrada = Integer.parseInt(txtcilindrada.getText());
            Moto moto = new Moto(cilindrada, marca, modelo, cor, ano, chassi, renavam, placa, IdVeiculo);

            listaDeVeiculos.add(moto);

            JOptionPane.showMessageDialog(null, "Moto " + modelo + " adicionado com sucesso!");
            txtid.setText("");
            txtchassi.setText("");
            txtmodelo.setText("");
            txtplaca.setText("");
            txtcor.setText("");
            txtmarca.setText("");
            txtrenavam.setText("");
            txtanofab.setText("");
            txtid.setText("");
            txtcilindrada.setText("");
            txttipo.setText("");
            txteixos.setText("");
            btnsalvar.setEnabled(false);
        }}/*else{
         JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }*/

        if (tipoSelecionado.equals("carro")) {
           //if(validaCampoCarro() == true)
            if(validaCampoAutomovel() == true){
            int IdVeiculo = Integer.parseInt(txtid.getText());
            String chassi = txtchassi.getText();
            int ano = Integer.parseInt(txtanofab.getText());
            int renavam = Integer.parseInt(txtrenavam.getText());
            String marca = txtmarca.getText();
            String modelo = txtmodelo.getText();
            String cor = txtcor.getText();
            String placa = txtplaca.getText();
            String tipo = txttipo.getText();
            Automovel carro = new Automovel(tipo, marca, modelo, cor, ano, chassi, renavam, placa, IdVeiculo);

            listaDeVeiculos.add(carro);

            JOptionPane.showMessageDialog(null, "Automóvel " + modelo + " adicionado com sucesso!");
            txtid.setText("");
            txtchassi.setText("");
            txtmodelo.setText("");
            txtplaca.setText("");
            txtcor.setText("");
            txtmarca.setText("");
            txtrenavam.setText("");
            txtanofab.setText("");
            txtid.setText("");
            txtcilindrada.setText("");
            txttipo.setText("");
            txteixos.setText("");
            btnsalvar.setEnabled(false);
            }}/*else{ JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }//fim do carro*/
        
        
        if(validaCampoCaminhao() == true){
        if (tipoSelecionado.equals("caminhao")) {
            int IdVeiculo = Integer.parseInt(txtid.getText());
            String chassi = txtchassi.getText();
            int ano = Integer.parseInt(txtanofab.getText());
            int renavam = Integer.parseInt(txtrenavam.getText());
            String marca = txtmarca.getText();
            String modelo = txtmodelo.getText();
            String cor = txtcor.getText();
            String placa = txtplaca.getText();
            int quantidadeeixos = Integer.parseInt(txteixos.getText());
           // String tipo = txttipo.getText();
            Caminhao caminhao = new Caminhao(quantidadeeixos, marca, modelo, cor, ano, chassi, renavam, placa, IdVeiculo);

            listaDeVeiculos.add(caminhao);

            JOptionPane.showMessageDialog(null, "Caminhão " + modelo + " adicionado com sucesso!");
            txtid.setText("");
            txtchassi.setText("");
            txtmodelo.setText("");
            txtplaca.setText("");
            txtcor.setText("");
            txtmarca.setText("");
            txtrenavam.setText("");
            txtanofab.setText("");
            txtid.setText("");
            txteixos.setText("");
            txttipo.setText("");
            btnsalvar.setEnabled(false);
        }} /*else{ JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");//fim caminhao

        }    */ 
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void ckmotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckmotoActionPerformed
        txtcilindrada.setEnabled(true);
        txteixos.setEnabled(false);
        txttipo.setEnabled(false);
        ckcarro.setSelected(false);
        ckcaminhao.setSelected(false);
    }//GEN-LAST:event_ckmotoActionPerformed

    private void ckcaminhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckcaminhaoActionPerformed
        txtcilindrada.setEnabled(false);
        txteixos.setEnabled(true);
        txttipo.setEnabled(false);
        ckcarro.setSelected(false);
        ckmoto.setSelected(false);
    }//GEN-LAST:event_ckcaminhaoActionPerformed

    private void ckcarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckcarroActionPerformed
        txtcilindrada.setEnabled(false);
        txteixos.setEnabled(false);
        txttipo.setEnabled(true);
        ckmoto.setSelected(false);
        ckcaminhao.setSelected(false);
    }//GEN-LAST:event_ckcarroActionPerformed

    private void btnproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproximoActionPerformed
        contadorDePagina = contadorDePagina + 1;
        String tipoAtual = listaDeVeiculos.get(contadorDePagina).getClass().toString();
        if (tipoAtual.equals("class Model.Moto")) {
            Moto moto = (Moto) listaDeVeiculos.get(contadorDePagina);
            txtanofab.setText(String.valueOf(moto.getAnoFab()));
            txtmarca.setText(moto.getMarca());
            txtid.setText(String.valueOf(moto.getIdVe()));
            txtrenavam.setText(String.valueOf(moto.getRenavam()));
            txtcor.setText(moto.getCor());
            txtmodelo.setText(moto.getModelo());
            txtchassi.setText(moto.getChassi());
            txtcilindrada.setText(String.valueOf(moto.getCilindradas()));
            ckmoto.setSelected(true);//habilia check da moto
            txttipo.setEnabled(false);//desabilitar campos que não são do objeto
            //Aqui devemos setar todos os txtx de uma moto
            //Habilitar o check "MOTO"
        } else if (tipoAtual.equals("class Model.Automovel")) {
            Automovel auto = (Automovel) listaDeVeiculos.get(contadorDePagina);
            txttipo.setText(auto.getTipoAuto());
            txtanofab.setText(String.valueOf(auto.getAnoFab()));
            txtmarca.setText(auto.getMarca());
            txtid.setText(String.valueOf(auto.getIdVe()));
            txtrenavam.setText(String.valueOf(auto.getRenavam()));
            txtcor.setText(auto.getCor());
            txtmodelo.setText(auto.getModelo());
            txtchassi.setText(auto.getChassi());            
            ckcarro.setSelected(true);
            txttipo.setEnabled(true);
            //Aqui devemos setar todos os txtx de uma moto **** feito
            //Habilitar o check "AUTOMOVEL" *** feito
        } else {//mesa coisa para o caminhão
            Caminhao caminhao = (Caminhao) listaDeVeiculos.get(contadorDePagina);
            txteixos.setText(String.valueOf(caminhao.getQuantDeEixos()));
            txtanofab.setText(String.valueOf(caminhao.getAnoFab()));
            txtmarca.setText(caminhao.getMarca());
            txtid.setText(String.valueOf(caminhao.getIdVe()));
            txtrenavam.setText(String.valueOf(caminhao.getRenavam()));
            txtcor.setText(caminhao.getCor());
            txtmodelo.setText(caminhao.getModelo());
            txtchassi.setText(caminhao.getChassi());
            ckcaminhao.setSelected(true);
            txttipo.setEnabled(false);
             //Aqui devemos setar todos os txtx de uma moto *** feito
            //Habilitar o check "CAMINHAO" **** feito
        }


    }//GEN-LAST:event_btnproximoActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed
       contadorDePagina = contadorDePagina - 1;
        String tipoAtual = listaDeVeiculos.get(contadorDePagina).getClass().toString();
        if (tipoAtual.equals("class Model.Moto")) {
            Moto moto = (Moto) listaDeVeiculos.get(contadorDePagina);
            txtanofab.setText(String.valueOf(moto.getAnoFab()));
            txtmarca.setText(moto.getMarca());
            txtid.setText(String.valueOf(moto.getIdVe()));
            txtrenavam.setText(String.valueOf(moto.getRenavam()));
            txtcor.setText(moto.getCor());
            txtmodelo.setText(moto.getModelo());
            txtchassi.setText(moto.getChassi());
            txtcilindrada.setText(String.valueOf(moto.getCilindradas()));
            ckmoto.setSelected(true);//habilia check da moto
            txttipo.setEnabled(false);//desabilitar campos que não são do objeto
            //Aqui devemos setar todos os txtx de uma moto
            //Habilitar o check "MOTO"
        } else if (tipoAtual.equals("class Model.Automovel")) {
            Automovel auto = (Automovel) listaDeVeiculos.get(contadorDePagina);
            txttipo.setText(auto.getTipoAuto());
            txtanofab.setText(String.valueOf(auto.getAnoFab()));
            txtmarca.setText(auto.getMarca());
            txtid.setText(String.valueOf(auto.getIdVe()));
            txtrenavam.setText(String.valueOf(auto.getRenavam()));
            txtcor.setText(auto.getCor());
            txtmodelo.setText(auto.getModelo());
            txtchassi.setText(auto.getChassi());            
            ckcarro.setSelected(true);
            txttipo.setEnabled(true);
            
            //Aqui devemos setar todos os txtx de uma moto ***** feito
            //Habilitar o check "AUTOMOVEL" **** feito
        } else {
            Caminhao caminhao = (Caminhao) listaDeVeiculos.get(contadorDePagina);
            txteixos.setText(String.valueOf(caminhao.getQuantDeEixos()));
            txtanofab.setText(String.valueOf(caminhao.getAnoFab()));
            txtmarca.setText(caminhao.getMarca());
            txtid.setText(String.valueOf(caminhao.getIdVe()));
            txtrenavam.setText(String.valueOf(caminhao.getRenavam()));
            txtcor.setText(caminhao.getCor());
            txtmodelo.setText(caminhao.getModelo());
            txtchassi.setText(caminhao.getChassi());
            ckcaminhao.setSelected(true);
            txttipo.setEnabled(false);
             //Aqui devemos setar todos os txtx de uma moto **** feito
            //Habilitar o check "CAMINHAO" *** feito
        }
    }//GEN-LAST:event_btnanteriorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            btnsalvar.setEnabled(true);
            txtanofab.setText("");
            txtid.setText("");
            txtmodelo.setText("");
            txtplaca.setText("");
            txtcor.setText("");
            txtmarca.setText("");
            txtrenavam.setText("");
            txteixos.setText("");
            txttipo.setText(""); 
            txtchassi.setText("");
       //limpar todos os campos de texto *** feito
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chassi;
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnproximo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JCheckBox ckcaminhao;
    private javax.swing.JCheckBox ckcarro;
    private javax.swing.JCheckBox ckmoto;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtanofab;
    private javax.swing.JTextField txtchassi;
    private javax.swing.JTextField txtcilindrada;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txteixos;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtrenavam;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
